- name: Configure cluster common parts
  hosts:
    - masters
    - nodes
    - etcd
    - lbs
    - nfsservers
  become: yes
  roles:
    - base
    - cluster_common

- name: Configure cluster masters
  hosts:
    - masters
  become: yes
  roles:
    - cluster_master

- name: Configure openshift VMs
  hosts:
    - masters
    - nodes
    - lbs
  become: yes
  roles:
    - role: lvm_storage

    - role: docker_host
      docker_lvol_vg_name: "vg_data"
      docker_lvol_size: "99%FREE"

- name: Configure openshift masters
  hosts:
    - masters
  become: yes
  roles:
    - openshift_master

- name: Configure openshift nodes
  hosts:
    - nodes
  become: yes
  roles:
    - openshift_node

- name: Prepare nfs server for OpenShift NFS playbook
  hosts:
    - nfsservers
  become: yes
  roles:
    - lvm_storage
    - nfs_server

- name: Create temporary files on a RAM disk for TLS certs and keys
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - include: environment_context.yml
    - name: Create a temporary directory on the RAM disk
      file:
        path: "/dev/shm/{{ cluster_name }}"
        state: directory
        mode: 0700
    - name: Place TLS certificate under temp dir
      copy:
        dest: "/dev/shm/{{ cluster_name }}/{{ openshift_public_hostname }}.crt"
        content: "{{ tls_certificate }}"
        mode: 0600
    - name: Place TLS key under temp dir
      copy:
        dest: "/dev/shm/{{ cluster_name }}/{{ openshift_public_hostname }}.key"
        content: "{{ tls_secret_key }}"
        mode: 0600
    - name: Place CA cert under temp dir
      copy:
        dest: "/dev/shm/{{ cluster_name }}/ext_ca.crt"
        content: "{{ tls_ca_certificate }}"
        mode: 0600
